IMAGES = {
    "游戏窗口任务追踪": 'window_renwu_icon.png',
    "游戏窗口左上角": 'window_left_sign.png',
    "道具栏": "window_daoju_top.png",
    "摄妖香": 'daoju_xiang.png',
    "飞行符": "daoju_feixingfu.png",
    "飞行符打开界面": "window_feixing_pannel.png",
    "旗子傲来国": "daoju_qi_al.png",
    "旗子长安城": "daoju_qi_ca.png",
    "旗子长寿村": "daoju_qi_cs.png",
    "旗子朱紫国": "daoju_qi_zz.png",
    "小地图打开": "window_tab_map_open.png",
    "小地图出入口按钮": "window_map_introfront.png",
    "NPC驿站老板": ["npc_yz1.png", "npc_yz2.png", "npc_yz3.png", "npc_yz4.png"],
    "战斗中标记": "window_zhandou_mask.png",
    "狮子队标": "duibiao.png",
    "天眼通符": "daoju_yan.png"
}

IMAGES_FENGYAO = {
    "葫芦宝贝1": "fengyao_hulu1.png",
    "葫芦宝贝2": "fengyao_hulu2.png",
    "狂暴1": "fengyao_kuangbao1.png",
    "狂暴2": "fengyao_kuangbao2.png",
    "狂暴3": "fengyao_kuangbao3.png",
    "蝎子1": "fengyao_xiezi1.png",
    "蝎子2": "fengyao_xiezi2.png",
    "猫1": "fengyao_mao1.png",
    "猫2": "fengyao_mao2.png",
    "混沌兽1": "fengyao_hundun1.png",
    "封妖刷新": 'fengyaoshuaxing.png',
    '封妖任务1': 'fengyao_renwu.png',
    '封妖任务2': 'fengyao_renwu2.png',
    '封妖任务3': 'fengyao_renwu3.png',
    '封妖任务4': 'fengyao_renwu4.png',
}
